name: build-signpath

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+

jobs:
  build-signpath:
    environment:
      name: signpath
      deployment: false
    uses: ./.github/workflows/reusable-build.yml
    with:
      version: ${{ github.ref_name }}
      sign: true
    secrets:
      signpath_api_key: ${{ secrets.SIGNPATH_API_KEY }}
